services:
  - type: web
    name: zagonel-kpi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --worker-class sync
    envVars:
      - key: API_KEY
        value: zagonel2026
      - key: GITHUB_TOKEN
        value: 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
      - key: GITHUB_REPO
        value: BrunoPedrolo/zagonel-kpi
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
